openapi: 3.0.3
info:
  title: parse_cnab_file
  version: 1.0.0
  description: Esse é um projeto que permite a conversão de um arquivo cnab simples
    por meio de requisições normais e upload de arquivos txt
paths: {}
components: {}
