# Generated by Django 4.1.5 on 2023-01-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParseCnab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_transaction', models.IntegerField(choices=[(1, 'Débito'), (2, 'Boleto'), (3, 'Financiamento'), (4, 'Crédito'), (5, 'Recebimento Empréstimo'), (6, 'Vendas'), (7, 'Recebimento TED'), (8, 'Recebimento DOC'), (9, 'Aluguel')])),
                ('date', models.CharField(max_length=8)),
                ('value', models.CharField(max_length=10)),
                ('CPF', models.CharField(max_length=11)),
                ('card', models.CharField(max_length=12)),
                ('hour', models.CharField(max_length=6)),
                ('owner', models.CharField(max_length=14)),
                ('store_name', models.CharField(max_length=19)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
