# Generated by Django 4.1.5 on 2023-01-24 21:02

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("parse", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parsecnab",
            options={},
        ),
        migrations.RemoveField(
            model_name="parsecnab",
            name="CPF",
        ),
        migrations.RemoveField(
            model_name="parsecnab",
            name="file",
        ),
        migrations.RemoveField(
            model_name="parsecnab",
            name="store_name",
        ),
        migrations.RemoveField(
            model_name="parsecnab",
            name="type_of_transaction",
        ),
        migrations.AddField(
            model_name="parsecnab",
            name="name",
            field=models.TextField(default="exec", max_length=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parsecnab",
            name="type",
            field=models.IntegerField(
                default=40,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="parsecnab",
            name="card",
            field=models.TextField(
                max_length=12,
                validators=[
                    django.core.validators.MinLengthValidator(12),
                    django.core.validators.MaxLengthValidator(12),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="parsecnab",
            name="date",
            field=models.TextField(
                max_length=8,
                validators=[
                    django.core.validators.MinLengthValidator(8),
                    django.core.validators.MaxLengthValidator(8),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="parsecnab",
            name="hour",
            field=models.TextField(
                max_length=6,
                validators=[
                    django.core.validators.MinLengthValidator(6),
                    django.core.validators.MaxLengthValidator(6),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="parsecnab",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="parsecnab",
            name="owner",
            field=models.TextField(max_length=14),
        ),
        migrations.AlterField(
            model_name="parsecnab",
            name="value",
            field=models.TextField(max_length=10),
        ),
        migrations.AddField(
            model_name="parsecnab",
            name="cpf",
            field=models.TextField(
                default=1,
                max_length=11,
                validators=[
                    django.core.validators.MinLengthValidator(11),
                    django.core.validators.MaxLengthValidator(11),
                ],
            ),
            preserve_default=False,
        ),
    ]
